<a href="https://colab.research.google.com/github/kaybrian/Tensorflow_self_study/blob/main/NNs_with_sigmoid_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def sigmoid(sum):
  return 1/(1 + np.exp(-sum))

In [3]:
np.exp(1)

2.718281828459045

In [4]:
np.exp(2)

7.38905609893065

In [11]:
# testing the sigmoid fucntion
print(sigmoid(50))
print(sigmoid(30.5))
print(sigmoid(-25.5))

1.0
0.9999999999999432
8.423463754397692e-12


In [12]:
# implementing the sigmoid in the Neural networks
inputs = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])

In [13]:
inputs.shape

(4, 2)

In [14]:
 outputs = np.array([[0],
                     [1],
                     [1],
                     [0]])

In [15]:
outputs.shape

(4, 1)

In [26]:
weights0 = np.array([[-0.424, -0.740, -0.961],
                     [0.358, -0.577, -0.469]])

In [17]:
weights0.shape

(2, 3)

In [18]:
weights1 = np.array([[-0.017],
                     [-0.893],
                     [0.148]])

In [19]:
weights1.shape

(3, 1)

In [23]:
# number of times we are going to train the model
epochs = 100

In [22]:
# making the calculations for the data and work
for epoch in epochs:
  print(epoch)

SyntaxError: incomplete input (<ipython-input-22-ffb8e8d991d9>, line 3)

In [24]:
input_layer = inputs
input_layer

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [27]:
sum_synape0 = np.dot(input_layer, weights0)
sum_synape0

array([[ 0.   ,  0.   ,  0.   ],
       [ 0.358, -0.577, -0.469],
       [-0.424, -0.74 , -0.961],
       [-0.066, -1.317, -1.43 ]])

In [28]:
hidden_layer = sigmoid(sum_synape0)
hidden_layer

array([[0.5       , 0.5       , 0.5       ],
       [0.5885562 , 0.35962319, 0.38485296],
       [0.39555998, 0.32300414, 0.27667802],
       [0.48350599, 0.21131785, 0.19309868]])