In [1]:
import tensorflow as tf 

/home/it/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/it/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/it/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/it/.local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: P

In [2]:
print(tf.__version__)

1.12.0


In [3]:
hello = tf.constant('Hello, TensorFlow!')

In [4]:
word = tf.constant('word')


In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello + word)
    print(result)

b'Hello, TensorFlow!word'


In [9]:
a = tf.constant(10)
b = tf.constant(20)

In [10]:
a + b 

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [11]:
with tf.Session() as sess:
    result = sess.run(a + b)
    print(result)

30


In [12]:
const = tf.constant(10)
fill_mat = tf.fill((4,4), 10)

In [13]:
my_zeros = tf.zeros((4,4))

In [14]:
my_ones = tf.ones((4,4))

In [15]:
my_randn = tf.random_normal((4,4), mean=0, stddev=1.0)


In [16]:
myranduni = tf.random_uniform((4,4), minval=0, maxval=1)

In [17]:
my_ones

<tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>

In [18]:
my_ops = [const, fill_mat, my_zeros, my_ones, my_randn, myranduni]

In [19]:
my_ops

[<tf.Tensor 'Const_4:0' shape=() dtype=int32>,
 <tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>,
 <tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>]

In [20]:
sess = tf.InteractiveSession()

In [21]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-2.5015123   0.4321604   0.13240439  0.7130242 ]
 [ 0.02636021 -0.488124   -1.4247245   0.9624999 ]
 [ 0.6667505  -0.41106778 -0.944748    0.49282733]
 [-0.5294734  -1.7101399   2.14205    -0.01045302]]


[[0.7310661  0.36928678 0.9192039  0.21773899]
 [0.779896   0.3328054  0.27768326 0.9539623 ]
 [0.6813742  0.07731199 0.5843748  0.8476176 ]
 [0.7661637  0.46652234 0.16931283 0.29946625]]




In [22]:
a = tf.constant([[1,2],
                 [3,4]])

In [23]:
a.get_


shape()

TensorShape([Dimension(2), Dimension(2)])

In [24]:

b = tf.constant([[10], [100]])

In [25]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [26]:
result = tf.matmul(a,b)

In [27]:
sess.run(result)


array([[210],
       [430]], dtype=int32)