In [1]:
import tensorflow as tf


2024-05-24 13:45:03.556191: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-24 13:45:04.084679: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-24 13:45:07.759169: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-24 13:45:13.745048: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
tf.__version__

'2.16.1'

In [3]:
import numpy as np

In [6]:
# constants and varibales 
a = tf.constant([[20, 30], [40, 50]])

a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 30],
       [40, 50]], dtype=int32)>

In [7]:
a.shape

TensorShape([2, 2])

In [8]:
# getting the values of the constant
a.numpy()

array([[20, 30],
       [40, 50]], dtype=int32)

In [9]:
num_arr = np.array([[1, 2], [3, 4]])

In [10]:
num_arr = tf.constant(num_arr)

In [11]:
num_arr

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [12]:
# working with variables
var = tf.Variable([[10, 20], [30, 40]])
var    


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [13]:
var.numpy()

array([[10, 20],
       [30, 40]], dtype=int32)

In [14]:
# changing a value in the variable
var[0, 0].assign(100)


<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[100,  20],
       [ 30,  40]], dtype=int32)>

In [15]:
var

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[100,  20],
       [ 30,  40]], dtype=int32)>

In [16]:
# operations with tensors 
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [17]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [18]:
# multiplying tensors
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [19]:
# using numpy functions on the tensorflow 
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [25]:
tensor2 = np.sqrt(tensor)

In [26]:
# using tensorflow functions on the tensor
np.dot(tensor, tensor2)

array([[ 4.46410162,  5.41421356],
       [ 9.92820323, 12.24264069]])

In [27]:
# working with  strings in tf 2.0 
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

In [28]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [29]:
tf.strings.unicode_decode(tf_string, "UTF8")


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

In [30]:
# storing the arrays of the strings
tf_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
tf_array

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'TensorFlow', b'Deep Learning', b'AI'], dtype=object)>

In [33]:
for string in tf_array:
    print(string)
    print(tf.strings.length(string))

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)
tf.Tensor(b'AI', shape=(), dtype=string)
tf.Tensor(2, shape=(), dtype=int32)
